version: '3.4'

services:
  twitchbot:
    image: twitchbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 443:443
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "bot.js"]
